### ISSUE TITLE
安卓5.1.1设备上无法向桌面添加小部件

### ISSUE THREAD

**Issue by skyclouds** [yuchuangu85/Launcher3_mx#1]
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.appwidget.action.APPWIDGET_BIND (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1808)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1528)
        at android.app.Activity.startActivityForResult(Activity.java:3788)
        at android.app.Activity.startActivityForResult(Activity.java:3749)
        at neso.launcher3.Launcher.startActivityForResult(Launcher.java:2058)
        at neso.launcher3.Launcher.addAppWidgetFromDrop(Launcher.java:2388)
        at neso.launcher3.Launcher.addPendingItem(Launcher.java:2301)
        at neso.launcher3.Workspace$11.run(Workspace.java:3492)
        at neso.launcher3.Workspace$12.run(Workspace.java:3687)
        at neso.launcher3.DragLayer$3.onAnimationEnd(DragLayer.java:787)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1171)
        at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:722)
        at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:738)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
        at android.view.Choreographer.doCallbacks(Choreographer.java:586)
        at android.view.Choreographer.doFrame(Choreographer.java:555)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5271)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)

**Comment by yuchuangu85** [comment]
@skyclouds 我这没有5.1.1的设备，没办法测试，不过你检查一下提示的代码，还有就是权限问题。

**Comment by yuchuangu85** [comment]
@skyclouds 
参考一下这个链接：https://www.cnblogs.com/liyiran/p/4557446.html
